<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کار با آرایه
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نمایه‌سازی (indexing)
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای دسترسی به یک خانه‌ی دلخواه آرایه، می‌توان مختصات آن را داخل <code>[]</code> قرار داد. مشابه لیست پایتون، شماره‌ها از صفر آغاز می‌شوند و شماره‌ی منفی به معنای شروع از انتهای آرایه است.
</font>
</p>

In [2]:
a = np.array([0, 1, 2, 3])
print(a)
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

[0 1 2 3]
a[0] = 0
a[2] = 2
a[-1] = 3


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای دسترسی به خانه‌ای از یک آرایه‌ی نامپای چندبعدی، کافیست مختصات بعُدها را با ویرگول <code>(,)</code> از هم جدا کنید.
</font>
</p>

In [2]:
a = np.random.randint(0, 10, (3, 5))
print(a)
print('a[2, 3] =', a[2, 3])

[[5 1 7 8 5]
 [8 1 8 3 8]
 [9 8 4 1 4]]
a[2, 3] = 1


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    هم‌چنین می‌توانید مقدار یک خانه را ضمن دسترسی به آن تغییر دهید.
</font>
</p>

In [3]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    دقت داشته باشید که چون آرایه نوع داده مشخصی دارد، مقداری که داخل یک خانه آن قرار می‌دهید در صورت امکان به نوع داده آرایه تبدیل می‌شود. برای مثال اگر در یک آرایه از جنس اعداد صحیح یک مقدار حقیقی قرار دهید، بخش صحیح عدد داخل آرایه قرار می‌گیرد.
</font>
</p>

In [4]:
a[2, 3] = 3.14
print('a[2, 3] =', a[2, 3])

a[2, 3] = 3


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
برش (slicing)
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای دسترسی به زیرآرایه‌های یک آرایه نامپای، می‌توان مثل لیست پایتون آن را برش داد و ابتدای برش، انتهای برش و گام‌ برش را با دونقطه <code>(:)</code> از هم جدا کرد. در صورت مشخص نکردن این مقادیر، مقدار پیش‌فرض (صفر برای شروع، اندازه آرایه برای پایان و یک برای گام پرش) برای هر یک لحاظ می‌شود.
</font>
</p>

In [6]:
a = np.array([0, 1, 2, 3, 4])
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    مشابه نمایه‌سازی می‌توانیم برش‌ها را برای هر بُعد مشخص کنیم و آن‌ها را با ویرگول <code>(,)</code> از هم جدا کنیم. به این ترتیب به یک برش از آرایه می‌رسیم که مرتبه (تعداد ابعاد) آن مشابه آرایه اصلی است.
</font>
</p>

In [7]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])
print(a[:2, 1:])
print(a[1:3, ::2])

[[1 2]
 [4 5]]
[[3 5]
 [6 8]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای دسترسی به زیرآرایه‌های با مرتبه (تعداد ابعاد) پایین‌ترِ آرایه می‌توانیم از ترکیب نمایه‌سازی و برش استفاده کنیم. برای مثال <code>a[:2, 1]</code> یک برش دوتایی از ابتدای بُعد نخست می‌دهد و از بُعد دوم هم مختصات <code>1</code> را نمایه‌سازی می‌کند و زیرآرایه حاصل را اختیارمان می‌گذارد. بُعد اول که حاصل برش است حفظ می‌شود و بُعد دوم که نمایه‌سازی شده از بین می‌رود. در نتیجه این زیرآرایه، یک آرایه تک‌بعدی با اندازه ۲ خواهد بود. این مثال و مثال‌های دیگری را در کد زیر مشاهده می‌کنید. 
</font>
</p>

In [8]:
print(a[:2, 1])
print(a[2, :])
print(a[:, 1])
print(a[2])

[1 4]
[6 7 8]
[ 1  4  7 10]
[6 7 8]



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    همان‌طور که می‌بینید علامت دونقطه خالی (<code>:</code>) به معنای برش و انتخاب کل یک بعد است و اگر تعدادی از ابعاد آخر به این شکل برش خورده باشند می‌توان از ذکر آن‌ها چشم‌پوشی کرد (<code>a[2, :]</code> معادل <code>a[2]</code> است).
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یک نکته مهم و کاربردی درباره نمایه‌سازی و برش آرایه‌ها در نامپای این است که حاصل آن‌ها یک دید (view) به زیرآرایه‌ای از آرایه اصلی در اختیارمان می‌گذارد، و برخلاف لیست پایتون یک کپی از آن تولید نمی‌کند. بدین معنا که با تغییر دادن زیرآرایه‌ی حاصل، آرایه اصلی نیز تغییر می‌کند. مثالی از آن را در کد زیر مشاهده می‌کنید.
</font>
</p>

In [9]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_a = a[1:3, 1:]
sub_a[0, 0] = 10
print(a)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای کپی گرفتن از یک زیرآرایه می‌توانید متد <code>copy</code> را برای آن صدا بزنید.
</font>
</p>

In [10]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بازآرایی (reshaping)
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یک آرایه از پیش تعریف شده را می‌توان بازآرایی کرد و به آن ابعاد تازه‌ای داد؛ به شرط آن که اندازه‌ی آرایه برابر با اندازه حاصل از ابعاد داده‌شده باشد. برای این منظور کافیست متد <code>reshape</code> را برای آرایه صدا بزنیم و اندازه‌ی ابعاد تازه را در قالب یک چندتایی یا یک عدد (برای آرایه تک‌بعدی) به آن ورودی دهیم. به عنوان مثال به کمک کد زیر می‌توانیم یک آرایه‌ی تک‌بعدی با طول 16 را به شکل یک آرایه‌ی دوبعدی با ابعاد 4 در 4 بازآرایی کنیم.
</font>
</p>

In [5]:
a = np.arange(16)
print(a)
print(a.reshape(4, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به عنوان مثال دیگر می‌توان یک آرایه تک‌بعدی را بازآرایی کرده و آن را به‌گونه‌ای دوبعدی کرد که اندازه‌ی یک بُعد آن یک شود.
</font>
</p>

In [12]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))
print(a.reshape(1, 3))

[[1]
 [2]
 [3]]
[[1 2 3]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اگر برای بازآرایی اندازه‌ی دقیقاً یکی از بعدها را معادل با <code>1-</code> ورودی دهیم آنگاه نامپای از روی اندازه‌ی آرایه و اندازه‌ی سایر ابعاد ورودی، اندازه‌ آن بعد را تشخیص خواهد داد.
</font>
</p>

In [13]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    بسیاری از مواقع پیش می‌آید که قصد داریم یک آرایه‌ی چندبعدی را به یک آرایه‌ی تک‌بعدی تبدیل کنیم. به چنین کاری مسطح‌سازی (Flattening) گفته می‌شود و به راحتی با متد بازآرایی نامپای قابل انجام است.
</font>
</p>

In [14]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a.reshape(-1))

[0 1 2 3 4 5 6 7 8]


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ترانهادن (transpose)
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    جدا از بازآرایی، ترتیب ابعاد یک آرایه را نیز می‌توان تغییر داد. با صدا زدن متد <code>T</code> یا <code>transpose</code> (بدون ورودی) ترتیب ابعاد آرایه برعکس می‌شود. برای مثال با برعکس کردن بعدهای یک آرایه دوبعدی جای سطرها و ستون‌های آن عوض می‌شود. بنابراین اگر آرایه دوبعدی را یک ماتریس در نظر بگیریم، ماتریس ترانهاده به دست می‌آید. 
</font>
</p>

In [15]:
a = np.arange(8).reshape(2, 4)
print(a)
print(a.T)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    می‌توان ترتیب دلخواهی را هم با ورودی دادن به متد <code>transpose</code> اعمال کرد. آرایه زیر از اعداد 0 تا 23 را در نظر بگیرید. 
</font>
</p>

In [16]:
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این آرایه سه بعد دارد که به ترتیب اندازه‌های 2، 3 و 4 دارند و برای اشاره به هر خانه از آن به ترتیب باید مختصات خانه در این بعدها را تعیین کنیم. برای مثال عدد 23 در خانه <code>a[1, 2, 3]‍</code> قرار دارد. حال اگر متد <code>transpose</code> را برای <code>a</code> صدا بزنیم و ترتیب تازه‌ای را به آن ورودی دهیم، ترتیب بعدها تغییر می‌کند. 
</font>
</p>

In [17]:
a.transpose(1, 2, 0)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در کد فوق با صدا زدن <code>a.transpose(1, 2, 0)</code>، بُعد دوم (شماره 1) تبدیل به بُعد اول آرایه جدید، بُعد سوم (شماره 2) تبدیل به بُعد دوم آرایه جدید و بُعد نخست (شماره 0) تبدیل به بُعد سوم آرایه جدید می‌شود. به این ترتیب اندازه ابعاد آرایه جدید به ترتیب 3، 4 و 2 خواهد بود و عدد 23 این بار در خانه <code>[2, 3, 1]</code> قرار می‌گیرد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اگر بخواهیم تنها دو تا از بعدها را با هم جابجا کنیم می‌توانیم از متد <code>swapaxes</code> استفاده کنیم و شماره‌ی دو بعد آرایه (با شروع از 0) را به آن ورودی دهیم. 
</font>
</p>

In [18]:
a.swapaxes(0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
به هم دوختن (concatenate) و شکافتن (split) آرایه‌ها
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای به هم دوختن چند آرایه می‌توان از تابع <code>concatenate</code> استفاده کرد. به این شکل که در یک لیست تعدادی آرایه به آن می‌دهیم تا آرایه‌ها را در جهت محوری که با پارامتر <code>axis</code> مشخص می‌شود (به طور پیش‌فرض محور نخست) به هم بدوزد. آرایه‌های داده‌شده باید در جهت سایر محورها ابعاد یکسانی داشته باشند.
</font>
</p>

In [19]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
np.concatenate([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    عملیات شکافتن یک آرایه به لیستی از چند آرایه که برعکس دوختن است را می‌توان به کمک تابع <code>split</code> انجام داد. این تابع یک آرایه را در جهت محوری که با <code>axis</code> مشخص می‌شود (به طور پیش‌فرض محور نخست) از نقاطی که با یک لیست به آن داده شده می‌شکافد. 
</font>
</p>

In [21]:
a = np.arange(10)
x, y, z = np.split(a, [2, 5])
print(x)
print(y)
print(z)

[0 1]
[2 3 4]
[5 6 7 8 9]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به جای نقاط برش می‌توان یک عدد ورودی داد تا آرایه به آن تعداد آرایه با ابعاد برابر تقسیم شود. اما اندازه بعد آرایه در راستای محور <code>axis</code> باید حتماً بر این عدد بخش‌پذیر باشد تا بتوان آرایه را به تکه‌های برابر تقسیم کرد. 
</font>
</p>

In [22]:
a = np.arange(12).reshape(2, 6)
x, y, z = np.split(a, 3, axis=1)
print(x)
print(y)
print(z)

[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]
