<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توابع تجمیعی
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای توصیف داده معمولا از آماره‌هایی چون میانگین و انحراف معیار استفاده می‌شود که داده را در قالب اعداد توصیف می‌کنند. به توابعی از این دست که درباره یک مجموعه از داده یک عدد گزارش می‌کنند، توابع تجمیعی می‌گوییم. توابعی چون مجموع (sum) ، کمینه (min) و بیشینه (max) همگی از این شمارند. نمونه‌ای از استفاده از این توابع را در کد زیر مشاهده می‌کنید.

</font>
</p>

In [3]:
a = np.random.randint(0, 10, 20)
print(a)
print('sum =', np.sum(a))
print('min =', np.min(a))
print('max =', np.max(a))

[5 1 7 8 5 8 1 8 3 8 9 8 4 1 4 4 1 7 3 1]
sum = 96
min = 1
max = 9


In [4]:
print(a.min(), a.max(), a.sum())

1 9 96


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یک نکته حائز اهمیت این است که توابع تجمیعی‌ای چون موارد فوق، داخل خود پایتون هم پیاده‌سازی شده‌اند و کار مشابهی را انجام می‌دهند؛ اما توابع تجمیعی نامپای به خاطر استفاده از کدهای کامپایل شده برای انجام محاسبات، بسیار سریع‌تر عمل می‌کنند (نمونه‌ای از این مقایسه را در کد زیر مشاهده می‌کنید) و هم‌چنین برای آرایه‌های چندبعدی مناسب‌ترند. از این رو بهتر است تا جای ممکن از توابع داخل نامپای استفاده کنیم.
</font>
</p>

In [5]:
big_array = np.random.rand(1000*1000)
%timeit sum(big_array)
%timeit np.sum(big_array)

91.4 ms ± 1.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
584 µs ± 3.19 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
a = np.random.randint(0, 10, (3, 4))
print(a)

[[6 5 4 2]
 [0 1 4 5]
 [0 3 1 9]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
توابع تجمیعی نامپای را می‌توان برای آرایه‌های چندبعدی هم به کار برد. به طور پیش‌فرض این توابع نتیجه را در قالب یک عدد برای همه خانه‌های آرایه گزارش می‌کنند.
    <br>
      با تعیین محور تجمیع می‌توان این کار را در راستای تنها یک محور هم انجام داد. برای مثال اگر یک آرایه دو بعدی داشته باشیم و بخواهیم مقدار کمینه ستون‌ها را به صورت یک آرایه داشته باشیم، کافیست متد min را با ورودی axis=0 برای آرایه صدا بزنیم.  
</font>
</p>

In [8]:
a.sum()

40

In [9]:
a.min(axis=0)

array([0, 1, 1, 2])

In [10]:
a.max(axis=1)

array([6, 5, 9])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال مثالی برای استفاده از توابع تجمیعی برای گزارش توصیف‌هایی آماری از داده را بررسی می‌کنیم. این کار را روی داده قد بازیکنان ترکیب اولیه دو تیم ملی فوتبال ایران و اسپانیا در مسابقه گروهی جام جهانی ۲۰۱۸ روسیه انجام می‌دهیم. داده‌ها را در آرایه دو بعدی دو در یازده <code>heights</code> نگه داشته‌ایم که سطر نخست آن (<code>heights[0]</code>) مربوط به تیم ملی ایران و سطر دوم آن (<code>heights[1]</code>) متعلق به تیم ملی اسپانیاست. آماره‌ها را برای هر تیم جداگانه محاسبه می‌کنیم.
</font>
</p>

In [11]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]


In [12]:
print('Min:', np.min(heights, axis=1)) 
print('25th percentile:', np.percentile(heights, 25, axis=1)) 
print('Median:', np.median(heights, axis=1))
print('75th percentile:', np.percentile(heights, 75, axis=1))
print('Max:', np.max(heights, axis=1))

Min: [178 170]
25th percentile: [181.  171.5]
Median: [185. 176.]
75th percentile: [187. 187.]
Max: [194 194]
