<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توابع عمومی
</font>
</h1>

In [1]:
import numpy as np
np.random.seed(1400)


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    لازم به ذکر است از <code>np.random.seed</code> به منظور تولید اعداد شبه‌تصادفی (<i>pseudo-random</i>) استفاده می‌شود. با تعیین یک مقدار دلخواه برای آن، مولد اعداد تصادفی نامپای را به‌گونه‌ای تنظیم می‌کنیم که در هربار فراخوانی، اعداد مشابهی را خروجی دهد. در این نوت‌بوک به منظور رعایت تشابه خروجی کدهای درسنامه و کدی که شما اجرا خواهید کرد از این قابلیت استفاده شده است. 
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای مشاهده میزان بهینگی نامپای، عناصر دو آرایه را نظیر به نظیر با همدیگر جمع می‌کنیم.
    <br>
    یک بار از تابع <code>cal_sum</code> و بار دیگر با استفاده از نامپای این کار را انجام می‌دهیم تا بتوانیم نتیجه را مقایسه کنیم.
</font>
</p>

In [2]:
a = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
b = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9 
print('a =', a)
print('b =', b)

def cal_sum(a,b) :
    output = np.empty(len(a), dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output

print(cal_sum(a, b))

a = [5 1 7 8]
b = [5 8 1 8]
[10  9  8 16]


In [3]:
big_size = 10*1000*1000
a = np.random.randint(0, 10, big_size) 
b = np.random.randint(0, 10, big_size) 
%timeit cal_sum(a, b)

3.52 s ± 50.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.add(a, b) 

26.1 ms ± 286 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    طبق دو سلول بالا، اگر طول آرایه‌هایی که داریم ۱۰ میلیون باشد، چندین ثانیه طول می‌کشد تا فقط بتوانیم جمع عنصر به عنصر تنها دو آرایه را به‌دست آوریم (بسته به سیستم اجرا کننده ممکن است تفاوتی جزئی در زمان اجرا دیده شود). مشخصا اگر تعداد آرایه‌ها بیشتر شود یا عملیات پیچیده‌تری داشته باشیم، خیلی بیشتر از چند ثانیه طول می‌کشد تا محاسبات انجام شود. 
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
      کتابخانه نامپای برای این منظور توابع عمومی (<i>universal functions</i> یا به اختصار <i>ufunc</i>) را پیش‌بینی کرده است. در سلول زیر مقدار زمان مصرفی برای <i>ufunc</i> مربوط به جمع عنصر به عنصر را مشاهده می‌کنیم. تابع <code>np.add</code> یک <i>ufunc</i> برای جمع عنصر به عنصر دو آرایه است. این تابع در ورودی دو آرایه دریافت می‌کند و در خروجی آرایه‌ای قرار می‌دهد که عنصر i ام اش حاصل جمع عنصر i ام دو آرایه ورودی است.
</font>
</p>

In [6]:
a = np.random.randint(0, 10, 4) 
b = np.random.randint(0, 10, 4) 
print(np.add(a, b)) # قالب قبلی
print(a + b) # استفاده از عملگر معادل

[9 5 9 8]
[9 5 9 8]


In [8]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    علاوه بر <code>np.add</code>، نامپای توابع عمومی دیگری نیز دارد. برخی توابع عمومی، دو عملوند و برخی دیگر تنها یک عملوند را در ورودی می‌پذیرند. در ابتدا به برخی توابع دو عملوندی آن نگاهی بی‌اندازیم.
</font>
</p>

In [9]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


In [10]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


In [9]:
print('a / b =', np.divide(a, b)) 
print('a / b =', a / b) # است a / b معادل np.divide(a, b)

a / b = [-0.   0.1  2.   0.6]
a / b = [-0.   0.1  2.   0.6]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سلول‌های زیر، توابع عمومی‌ای را می‌بینیم که یک عملوند می‌پذیرند.
</font>
</p>

In [11]:
a = np.random.randint(0, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 0 تا 10
b = np.random.randint(-10, 11, 5) # آرایه‌ای شامل 5 عدد تصادفی در بازه 10- تا 10
print('a =', a)
print('b =', b)

a = [4 8 3 6 6]
b = [-8  6 -7  6  1]


In [11]:
print('absolute values of b =', np.abs(b)) 

absolute values of b = [8 6 7 6 1]


In [12]:
print('square values of a =', np.square(a) ) 

square values of a = [16 64  9 36 36]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ثابت <b>Not a Number</b> یا <code>nan</code> برای نشان دادن عدد نبودن مقدار یک خانه در آرایه عددی استفاده می‌شود. برای مثال اگر تابع <code>sqrt</code> برای یک خانه با مقدار <code>1-</code> صدا زده شود، حاصل <code>nan</code> خواهد شد.
</font>
</p>

In [12]:
np.seterr(invalid="ignore") # خطای ناشی از عملیات غیرمجاز را نادیده می‌گیرد
a = np.array([1 , 2 , -3 , 4, -5])
print('a = ', a)
print('isnan results for a =', np.isnan(a))
print('sqrt(a) = ', np.sqrt(a))
print('isnan resultes for sqrt(a) =', np.isnan(np.sqrt(a)))

a =  [ 1  2 -3  4 -5]
isnan results for a = [False False False False False]
sqrt(a) =  [1.         1.41421356        nan 2.                nan]
isnan resultes for sqrt(a) = [False False  True False  True]
