<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    نمایه‌سازی با آرایه‌ها
</font>
</h1>

In [1]:
import numpy as np

<h2 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    نمایه‌سازی با آرایه‌های بولی (boolean indexing)  
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش از این، استفاده از نتیجه‌ی مقایسه بین آرایه‌ها با استفاده از توابع خلاصه‌سازی چون <code>sum</code> را آموختیم. اما یک قابلیت دیگر نامپای که حاصل چنین مقایسه‌ای را ارزشمندتر می‌کند قابلیت نمایه‌سازی (indexing) از آرایه‌ها به وسیله‌ی آرایه‌های بولی است. به این ترتیب می‌توانیم به راحتی به یک زیرمجموعه از آرایه که ویژگی مشخصی دارد، دسترسی پیدا کنیم. دوباره به مسئله دمای هوای شهر شیراز که در درس‌نامه قبلی به آن پرداختیم، باز می‌گردیم.
</font>
</p>

In [2]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کافیست خط زیر را بنویسیم تا دمای هوا در روزهایی از آرایه فوق که دمای بین ۱۵ و ۲۰ دارند را در قالب یک آرایه یک‌بعدی داشته باشیم.
</font>
</p>

In [3]:
t[(t >= 15) & (t <= 20)]

array([17, 15, 15, 18, 19, 18, 17, 18, 20, 19, 20, 19])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در کدهای زیر، چند نمونه استخراج اطلاعات از داده به کمک این روش را مشاهده می‌کنید.
</font>
</p>

In [4]:
print('میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه:', t[t > 20].mean())
print('میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه:', np.median(t[(t > 15) & (t < 20)]))

میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه: 22.3
میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه: 18.0


In [7]:
calendar = np.arange(4*7).reshape(4, 7)
print(calendar)
holidays = (calendar%7 >= 5) # آرایه بولی متناظر روزهای آخر هفته (پنج‌شنبه و جمعه)
first_mid = (calendar < 2*7) # آرایه بولی متناظر روزهای دو هفته اول اردیبهشت
print('میانه دمای روزهای آخرِ هفته کل ماه:', np.median(t[holidays]))
print('میانه دمای دو هفته نخست ماه:', np.median(t[first_mid]))
print('میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه:', np.mean(t[~first_mid & holidays]))

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
میانه دمای روزهای آخرِ هفته کل ماه: 19.5
میانه دمای دو هفته نخست ماه: 15.0
میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه: 22.25


<h2 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    نمایه‌سازی با آرایه‌های عددی (fancy indexing)  
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    برای انتخاب بعضی عناصر آرایه، بر حسب جایگاهشان، استفاده از آرایه‌های عددی برای نمایه‌سازی کاربرد دارد.
    <br>
    برای مثال، اگر بخواهیم خانه‌های شماره ۲، ۳ و ۵ از یک آرایه یک بعدی را جدا کنیم، کافیست یک آرایه نمایه‌سازی دربرگیرنده این شماره‌ها بسازیم. سپس می‌توانیم به شکل زیر، آن را داخل براکت قرار دهیم تا خانه‌های مدنظرمان در قالب یک آرایه برگردانده شوند.
</font>
</p>

In [8]:
a = np.array([1, 2, 4, 8, 16, 32])
ind = [2, 3, 5]
a[ind]

array([ 4,  8, 32])


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    دقت کنید آرایه‌ای که برگردانده می‌شود، هم‌شکل با آرایه‌ی نمایه‌سازی است. در همین مثال فوق، اگر آرایه <code>ind</code> را دوبعدی تعریف کنیم، <code>a[ind]</code> هم دوبعدی خواهد بود و در هر خانه‌ی آن مقدار خانه‌ای از آرایه اصلی که در <code>ind</code> به شماره‌ی آن اشاره شده قرار می‌گیرد.
</font>
</p>

In [9]:
ind = np.array([[2, 3],
               [4, 1]])
a[ind]

array([[ 4,  8],
       [16,  2]])


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اگر آرایه‌مان دوبعدی باشد یک آرایه شامل شماره سطرها و یک آرایه شامل شماره ستون‌های خانه‌های درخواستی می‌سازیم و به شکل زیر آن‌ها را به ترتیب داخل براکت قرار می‌دهیم.
</font>
</p>

In [17]:
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  8, 10,  6])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    گذاشتن <code>np.newaxis</code> در جایی از براکت، به معنای اضافه کردن یک بُعد با اندازه یک به آرایه در آنجا است. برای مثال <code>row[:, np.newaxis]</code> معادل است با <code>row.reshape(4, 1)</code>.
</font>
</p>

In [19]:
print(row[:, np.newaxis])
print(col)
a[row[:, np.newaxis], col]

[[0]
 [2]
 [3]
 [2]]
[0 2 1 0]


array([[ 0,  2,  1,  0],
       [ 6,  8,  7,  6],
       [ 9, 11, 10,  9],
       [ 6,  8,  7,  6]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
هم‌چنین می‌توانیم ضمن نمایه‌سازی به این شیوه، آرایه مورد نظر را تغییر دهیم. مثلا با کد زیر می‌توانیم خانه‌های با مقدار زوج آرایه را ده برابر کنیم.
</font>
</p>

In [30]:
a = np.array([2, 1, 3, 4, 5])
a[a%2 == 0] *= 10
print(a)

[20  1  3 40  5]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به عنوان مثال دیگر، کد زیر خانه‌های شماره ۱، ۲ و ۴ آرایه‌ی حاصل از کد قبل را ده برابر می‌کند.
</font>
</p>

In [31]:
a[[1, 1, 2, 4]] *= 10
print(a)

[20 10 30 40 50]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    دقت کنید که در کد بالا اگر یک شماره را چند بار در آرایه نمایه‌سازی تکرار کنیم، به همان تعداد عملیات فوق رویش اجرا نمی‌شود. برای این منظور تابع عمومی <code>at</code> فراهم شده تا به کمک آن عملیات روی هر خانه با توجه به تعداد تکرارش در آرایه‌ی نمایه‌سازی انجام شود. شیوه‌ی استفاده از <code>at</code> را در کد زیر مشاهده می‌کنید.
</font>
</p>

In [32]:
np.add.at(a, [0, 0, 0, 1, 1, 2], 5)
print(a)

[35 20 35 40 50]
